name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"     # daily at UTC 00:00 — adjust if you want different cadence
  workflow_dispatch:         # lets you run it manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake SVG
        uses: Platane/snk@master
        with:
          # IMPORTANT: use your exact GitHub username (owner name) here
          github_user_name: Bheesham-Kumar-Sajnani
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publish snake to `output` branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
